### ISSUE TITLE
CellML Model class

### ISSUE THREAD

**Issue by martinjrobins** [martinjrobins/hobo#11]
It would be nice to have a class that implements a Model concept, which takes a cellml file (or string?) defining what the model is.

@MichaelClerx: you have some cellml conversion routines don't you. Would this be useful here?

**Comment by MichaelClerx** [comment]
I don't think we should go down this route in Hobo, as we're interested just in fitting. Why don't we keep the models are hardcoded things (i.e. define some model interface) and use existing CellML converters to help us write this code?

**Comment by martinjrobins** [comment]
yea, I'd be happy to go with that then. What do you use in terms of CellML converters? I've used the webpage interface before to get Matlab code.

**Comment by MichaelClerx** [comment]
That works! I'd always use Myokit, but that's cause its my own code :D 

It does CellML -> Myokit -> Python, so maybe not ideal. What code are you looking to convert?

**Comment by martinjrobins** [comment]
Not sure yet. I don't need it at the moment, just thinking for the future

**Comment by MichaelClerx** [comment]
Have added Myokit to the 'free' directory, will use it for some data processing and to generate test data from Kylie's models before converting them to a STAN format

**Comment by MichaelClerx** [comment]
Closing this for now
